config/routes.rb
Newsly::Engine.routes.draw do

	resources :newsletters do
		member do
			put 'send_test'
			put 'deliver'
			put 'deliver_batch'
		end
	end

	resources :templates do
		member do
			put	'send_test'
			put 'publish'
		end
	end

	match '/snippets' => 'snippets#index'

  get '/' => "newsletters#index"
end

app/models/newsly/liquid_model.rb
module Newsly
	class LiquidModel < ActiveRecord::Base

		validates_presence_of :body
		#
    # Puts the parse error from Liquid on the error list if parsing failed
    #
    def after_validation
      errors.add :internal_template, @syntax_error unless @syntax_error.nil?
    end


    ### Attributes
    attr_protected :internal_template


    #
    # body contains the raw internal_template. When updating this attribute, the
    # template parses the internal_template and stores the serialized object
    # for quicker rendering.
    #
    def body=(text)
      self[:body] = text
      begin
        @internal_template = Liquid::Template.parse(text)
        self[:internal_template] = [Marshal.dump(@internal_template)].pack('m*')
      rescue Liquid::SyntaxError => error
        @syntax_error = error.message
      end
    end

    ### Methods
    #
    # Renders body as Liquid Markup template
    #
    def render(options = {})
      internal_template.render options
    end


    private
      #
      # Returns a usable Liquid:Template instance
      #
      def internal_template
        return @internal_template unless @internal_template.nil?
        
        if self[:internal_template].blank?
          @internal_template = Liquid::Template.parse body
          self[:internal_template] = [Marshal.dump(@internal_template)].pack('m*')
          save
        else
          @internal_template = Marshal.load(self[:internal_template].unpack("m")[0])
        end

        @internal_template
      end



	end
end

app/models/newsly/newsletter.rb
# encoding: UTF-8
module Newsly
  class Newsletter < Newsly::LiquidModel
    set_table_name 'newsly_newsletters'
  	liquid_methods :title, :body

    validates_presence_of :title

    ### Methods

    #
    # return true if never sent or batch_sent
    #
    def draft?
      self.sent? || self.batch_sent? ? false : true
    end
 
    #
    # Returns the status a string. TODO, make nicer!
    #
    def status
      return "draft" if self.draft?
      return "sent" if self.sent?
      return "batch" if self.batch_sent?
    end

  end
end

app/models/newsly/template.rb
# encoding: UTF-8

module Newsly
  class Template < Newsly::LiquidModel
    set_table_name 'newsly_templates'
    liquid_methods :subject, :body

    validates_presence_of :subject
    #validates_presence_of :parent_id, :if => :original
    #validates original is never draft and

    
    ### Methods

    #
    # Takes a draft and copies information to the original
    #
    def publish
      original = Newsly::Template.find(self.parent_id)
      original.subject= self.subject
      original.body= self.body
      original.save
      original
    end
    
  end
end

app/controllers/newsly/application_controller.rb
module Newsly
  class ApplicationController < ActionController::Base
  	include ActionView::Helpers::DateHelper
  end
end

app/controllers/newsly/newsletters_controller.rb
module Newsly
  class NewslettersController < ApplicationController  

    respond_to :html, :json
    respond_to :text, :only => :preview
  

    before_filter :get_newsletter, :except => [:new, :index]
    
    def index
      @newsletters = Newsletter.order('created_at desc').all
    end

    def show
      if Resque.size(:newsletter) > 0 || Resque.size(:mail) > 0
        @queues_working = true
      end
      @recipient_groups = []
      for group in Newsly.recipient_groups
        group[2] ||= group[1].call(@newsletter.id).count
        @recipient_groups.push(group)
      end
    end

    def new
      @newsletter = Newsly::Newsletter.create(:title => "Nyhetsbrevs rubrik", :body => "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod.", :sent => false)
      redirect_to newsletter_url(@newsletter)
    end

    def update
      if @newsletter.update_attributes(params[:newsletter])
        render :text => "Last saved #{distance_of_time_in_words_to_now(Time.now, true)} ago"
      else
        render :text => "Kunde inte sparas"
      end
    end

    def send_test
      if Newsly::Mailer.build_newsletter(@newsletter.id, params[:to], Newsly.test_data).deliver
        render :text => "Okidoki"
      end
    end

    def deliver
      if params[:answer] == "DELIVER"
        Resque.enqueue(Newsly::NewsletterSender, @newsletter.id, params[:recipient_groups])
        @newsletter.sent = true
        @newsletter.save
        render :text => "NEWSLETTER DELIVERED"
      else
        render :text => "WARNING! Not sent, did you answer correctly?"
      end
    end

    def deliver_batch
      if params[:answer] == "BATCH"
        Resque.enqueue(Newsly::NewsletterBatchSender, @newsletter.id, params[:recipient_group], params[:batch_size])
        @newsletter.batch_sent = true
        @newsletter.save
        render :text => "BATCH DELIVERED"        
      else
        render :text => "WARNING! Not sent, did you answer correctly?"
      end  
    end

    def destroy
      @newsletter.destroy
      redirect_to newsletters_url
    end

    protected
      def get_newsletter
        @newsletter = Newsly::Newsletter.find(params[:id])
      end
  end
end

app/controllers/newsly/snippets_controller.rb
module Newsly
  class SnippetsController < ApplicationController

  	layout false

  	def index
  	end

  end
end

app/controllers/newsly/templates_controller.rb
# encoding: UTF-8
module Newsly
  class TemplatesController < ApplicationController
	
  	def index
  		@templates = Newsly::Template.where(:draft => false).order('friendly_name')
      @template_types = Newsly::Template.all.map(&:template_type).uniq
  	end

  	def show
      @template = Newsly::Template.where(:parent_id => params[:id], :draft => true).first
      if @template.nil?
        @template = Newsly::Template.find(params[:id]).dup
        @template.draft = true
        @template.parent_id = params[:id]
        @template.save
      end
  	end

  	def update
      @template = Newsly::Template.find(params[:id])
      if @template.update_attributes(params[:template])
        render :text => "Last saved #{distance_of_time_in_words_to_now(Time.now, true)} ago"
      else
        render :text => "Kunde inte sparas"
      end
    end

    def send_test
      @template = Newsly::Template.find(params[:id])
      if Newsly::Mailer.build_mail(@template.id, params[:to], Newsly.test_data).deliver
        render :text => "Okidoki"
      end

    end


    def publish
      @draft = Newsly::Template.find(params[:id])
      @draft.publish
      render :text => "Published"
    end

  end
end

app/helpers/newsly/application_helper.rb
module Newsly
  module ApplicationHelper
  end
end

app/views/layouts/mercury.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <title>Mercury Editor</title>
    <%= stylesheet_link_tag    'mercury', 'mercury_overrides' %>
    <%= javascript_include_tag 'mercury' %>
  </head>
  <body>
    <script type="text/javascript">
      var saveUrl = null;
      var options = {
        saveStyle: 'form',  // 'form', or 'json' (default json)
        saveMethod: 'put', // 'POST', or 'PUT', (create, vs. update -- default POST)
        visible: null     // if the interface should start visible or not (default true)
      };
      new Mercury.PageEditor(saveUrl, options)
    </script>
  </body>
</html>

app/views/layouts/newsly/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Newsly</title>
  <%= javascript_include_tag "jquery", "rails", "application" %>
  <%= stylesheet_link_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash[:notice] %>
  <div class="flash">  <%= flash[:notice] %> </div>
  <div class="clearfix"></div>
<% end %>
<div id="flash" class="flash"></div>
<div id="page">	
  <%= yield %>
  <div class="clearfix"></div>
</div>
</body>
</html>

app/views/newsly/_navigation.html.erb
<ul id="nav">
  <li class="<%= "active" if params[:controller] == "newsly/newsletters" %>"><%= link_to t('Newsletters'), newsletters_path %></li>
  <li class="<%= "active" if params[:controller] == "newsly/templates" %>"><%= link_to t('Templates'), templates_path %></li>
</ul>
<div class="clearfix"></div>  

app/views/newsly/newsletters/_sidebar.html.erb
<div id="sidebar">
	<ul class="links">
		<li><%= link_to '<em>☜</em> Back'.html_safe, newsletters_path %></li>	
		<li class="button">
			<%= link_to "<em>❖</em>Send test".html_safe, send_test_newsletter_path(@newsletter), :id => "send_test"%>
		</li>
		<% if @queues_working %>
			<div class="notice">Some workers are still working, delivering disabled for now! Please reload later!</div>

		<% elsif !@newsletter.sent? and @newsletter.persisted?%>
			<% if @recipient_groups.count > 0 %>
				<li class="groups">
					<form id="groupform" class="groupform">
						<h3>Recipient Groups</h3>
						<ul>
							<% @max_batch_size = 0 %>
							<% for group in @recipient_groups %>
								<% @max_batch_size = @max_batch_size + group[2] %>
								<li>
									<input type="checkbox" name="<%=group[0].to_s%>" value="<%=group[0].to_s%>" id="group_<%=group[0].to_s%>" data-max="<%= group[2] %>"/>
									<label for="group_<%=group[0].to_s%>"><%= group[0].to_s.humanize %> (<span class="count"><%= group[2] %></span>)</label>
								</li>
							<% end %>
						</ul>
					</form>
				</li>
				<li class="button range deliverbutton">
					<input type="text" data-max="<%= @max_batch_size %>" id="batch_size" />
					<%= link_to "<em>✈</em>Deliver Batch!".html_safe, deliver_batch_newsletter_path(@newsletter), :id => "deliver_batch"%>
				</li>
				<li class="button deliverbutton">
					<%= link_to "<em>✈</em>Deliver All!".html_safe, deliver_newsletter_path(@newsletter), :id => "deliver"%>
				</li>
			<% end %>
		<% end %>
	</ul>
	<div id="saved"></div>	
</div>

app/views/newsly/newsletters/index.html.erb
<%= render :partial => "/newsly/navigation" %>
<div id="content">
	<h2><%= t("Newsletters")%></h2>
	<table cellspacing="0" cellpadding="0">
	  <tbody>
			<% @newsletters.each do |newsletter| %>
			  <tr>
			    <td class="<%= newsletter.status%>"><%= newsletter.status %></td>
			    <td class="title"><%= link_to newsletter.title, newsletter %></td>
			    <td class="action">
			    	<%= link_to 'Destroy', newsletter, confirm: 'Are you sure?', method: :delete if newsletter.draft? %>
			    </td>
			  </tr>
			<% end %>
		</tbody>
	</table>
</div>
<div id="sidebar">
	<ul class="links">
		<li><%= link_to "<em>+</em>#{t('New Newsletter')}".html_safe, new_newsletter_path %></li>
	</ul>
</div>

app/views/newsly/newsletters/show.html.erb
<div id="content">
	<div id="newsletter" data-id="<%=@newsletter.id%>" data-url="<%=newsletter_path(@newsletter)%>">
		<h2 id="title" class="mercury-region" data-type="markupable"><%= @newsletter.title.html_safe %></h2>
		<div id="body" class="mercury-region" data-type="editable"><%=	@newsletter.body.html_safe %></div>
	</div>
</div>
<%= render 'sidebar' %>

<%= javascript_include_tag "newsletters" %>

app/views/newsly/snippets/index.html.erb
<div class="mercury-snippet-panel">
  <div class="filter">
    <input class="filter" type="text">
  </div>
  <ul>
    <li data-filter="name-snippet">
      <img alt="Mottagarens namn" data-snippet="person_name" src="/assets/mercury/default-snippet.png"/>
      <h4>Mottagarens namn</h4>
      <div class="description">Mottagarens namn visas i mailet. t.ex "Kim F"</div>
    </li>
  </ul>
</div>

app/views/newsly/templates/index.html.erb
<%= render :partial => "/newsly/navigation" %>
<div id="content">
	<h2><%= t("Templates")%></h2>
	<ul class="type_tabs">
		<li class="title">Show type:</li>
		<li class="active"><%= link_to "All", templates_url %></li>
		<% @template_types.each do |type| %>
			<li class="<%=type.nil? ? "notype" : type %>">
				<% if type.nil? %>
					<%= link_to "No Type", "#", :data => {:type => "notype"} %>
				<% else %>
					<%= link_to type, "#", :data => {:type => type}%>
				<% end %>
			</li>
		<% end %>
	</ul>
	<table cellspacing="0" cellpadding="0" id="templates">
	  <tbody>
			<% @templates.each do |template| %>
			  <tr class="<%= template.template_type.nil? ? "notype" : template.template_type%>">
			    <td class="title">
			    	<%= link_to template.friendly_name || template.name, template, :class => "friendly_name" %>
			    	<span class="type"><%=t(template.template_type)%></span>
			    	<span class="desc">Lorem ipsum dolor sit amet conseqteur dolor amet.</span>
			    </td>
			  </tr>
			<% end %>
		</tbody>
	</table>
</div>
<div id="sidebar">
</div>

<%= javascript_include_tag "templates" %>

app/views/newsly/templates/show.html.erb
<div id="content">
	<div id="template" data-id="<%=@template.id%>" data-url="<%=template_path(@template)%>">
		<h2 id="subject" class="mercury-region" data-type="markupable"><%= @template.subject.html_safe %></h2>
		<div id="body" class="mercury-region" data-type="editable"><%=	@template.body.html_safe %></div>
	</div>
</div>
<div id="sidebar">
	<ul class="links">
    <li class="buttons">
			<%= link_to "<em>❖</em>Test".html_safe, send_test_template_path(@template), :class => "remote" %>
			<%= link_to "<em>✈</em>Publish".html_safe, publish_template_path(@template), :class => "remote", :id => "publish" %>
		</li>

		<li><%= link_to '<em>☜</em> Back'.html_safe, templates_path %></li>
	</ul>
	<div id="saved"></div>		
</div>

<%= javascript_include_tag "templates" %>